### ISSUE TITLE
Please document the purpose

### ISSUE THREAD

**Issue by MartinMuzatko** [mixmaxhq/deyarn#3]
I don't see a clear benefit in doing this. Why does this exist? And what problem does it solve?

**Comment by LasaleFamine** [comment]
I think this is what we are looking for: https://mixmax.com/blog/to-yarn-and-back-again-npm

**Comment by wearhere** [comment]
Added the link to that post at top https://github.com/mixmaxhq/deyarn/commit/651323a08a397ebcc494df52cdcd86584b9d2141, thanks folks.
